name: Build paper
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: |
          bundle install
          bundle exec nanoc compile
      - run: |
          # setup the username and email.
          git config user.name "Pieter's GitHub Actions Bot"
          git config user.email "<pieter.colpaert@ugent.be>"
      - run: |
          # commit
          cp -r output/ docs/
          git add docs
          git commit -m "Build ${{ env.DATE }}"
          git push origin master
